version: "3.0"

services:
  redis:
    image: redis
    command: redis-server --requirepass 123456
    volumes:
      - ./redis/log:/usr/local/var/log
      - ./redis/data:/data
    restart: always
    ports:
      - 6379:6379
    networks:
      - admin

networks:
  admin: